#! /bin/sh

aesd_path="$(realpath "$(dirname $0)")"

case "$1" in
  start)
    echo "Starting aesdsocket"
#    start-stop-daemon -S -n aesdsocket -x /usr/bin/aesdsocket -- -d
    start-stop-daemon -S -n aesdsocket -x ${aesd_path}/aesdsocket -- -d
    ;;
  stop)
    echo "Stopping aesdsocket"
    start-stop-daemon -K -n aesdsocket
    ;;
  *)
    echo "Usage: $0 {start|stop}"
    exit 1
esac
exit 0
